version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    container_name: dchat-postgres
    restart: always
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d/
      - postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - '${POSTGRES_HOST_PORT}:5432'
    networks:
      - d-network
  server:
      build:
        context: .
      container_name: dchat
      networks:
        - d-network
      ports:
        - '7000:7000'
      depends_on:
        - postgres
      volumes:
        - .:/app
        - node_modules:/app/node_modules
        - dist:/app/dist
      env_file:
        - .env
      command: npm run dev
networks:
  d-network:
volumes:
  postgresql_data:
  node_modules:
  dist: